Refactored Dropbox
shipyardapp/shipyard-blueprints pull request #191
Opened 2024-03-15 13:32 UTC by johnathan-rodriguez

2024-03-18 15:17 UTC, wrp801 requested changes
Small changes around the log statements

2024-03-18 15:17 UTC, wrp801 commented on shipyard_blueprints/dropbox/shipyard_dropbox/dropbox.py
> +                f"Failed to authenticate using key. Message from Dropbox Server{e}"
Change the message to this for slightly easier readability:

```f"Failed to authenticate using key. Message from Dropbox Server: {e}"```

2024-03-18 15:17 UTC, wrp801 commented on shipyard_blueprints/dropbox/shipyard_dropbox/cli/download.py
> +                    client=client,
For consistency, upon completion have a log statement that says "Successfully downloaded file to <target_path>". For the `regex_match` you don't need to do that for each one, but you can say something like "Successfully downloaded all files"

2024-03-18 15:17 UTC, wrp801 commented on shipyard_blueprints/dropbox/shipyard_dropbox/cli/upload.py
> +                f"{len(matching_file_names)} files found. Preparing to download..."
Should be "Preparing to upload" instead

2024-03-18 15:17 UTC, wrp801 commented on shipyard_blueprints/dropbox/shipyard_dropbox/cli/upload.py
> +    except Exception as e:
Same comment as before, where upon completion have one more additional log statement that lets the user know that their file has been successfully uploaded to Dropbox

2024-03-20 04:30 UTC, johnathan-rodriguez commented
This is one of the blueprints that refer to the main branch but looks like it is currently broken since the download function was carried over twice. Blueprint is currently not being used. Should I point it back to the original https://github.com/shipyardapp/dropbox-blueprints repo

2024-03-21 02:15 UTC, wrp801 commented
This PR has a lot of changes to other vendors that are most likely the result of a stale branch. Try pulling in the latest commits from main and merging them to this

2024-03-25 17:56 UTC, closed without merging