Moved the Census blueprint to the mono repo and adjusted the cli to a…
shipyardapp/shipyard-blueprints pull request #44
Opened 2023-06-29 15:10 UTC by johnathan-rodriguez

…llow for an optional wait parameter

2023-06-29 16:59 UTC, wrp801 requested changes
Overall looks good, just a tiny change to make in the toml file

2023-06-29 16:59 UTC, wrp801 commented on shipyard_blueprints/census/pyproject.toml
>  shipyard-bp-utils = {path = "../shipyard-bp-utils"}
Add `develop = true` to any path dependency

2023-06-30 15:06 UTC, wrp801 commented
@johnathan-rodriguez any reason why you deleted the check_sync_cli.py file?

2023-06-30 15:27 UTC, johnathan-rodriguez commented
@wrp801 I thought we were removing the check sync and combining it with the trigger sync cli- do we want both for the new way?

2023-06-30 15:28 UTC, johnathan-rodriguez commented
the old check sync would exist in the old way of doing things so the legacy function should be intact

2023-06-30 15:29 UTC, wrp801 commented
Okay so what you’re proposing is to leave the check syncs tied to the old repos?

2023-06-30 15:29 UTC, johnathan-rodriguez commented
yes

2023-06-30 15:30 UTC, wrp801 approved these changes

2023-06-30 17:40 UTC, merged