Feature/improve logging and error handling
shipyardapp/shipyard-blueprints pull request #74
Opened 2023-09-21 14:52 UTC by johnathan-rodriguez

2023-09-21 14:53 UTC, johnathan-rodriguez commented on shipyard_blueprints/hubspot/shipyard_hubspot/hubspot_utils.py
> -    if column_type:
Made a change here to make the code slightly more efficient. Underlying logic should be unchanged

2023-09-22 15:12 UTC, forstmeier requested changes

2023-09-22 15:12 UTC, forstmeier commented on shipyard_blueprints/hubspot/shipyard_hubspot/hubspot_utils.py
> +            "property Please choose between HUBSPOT_OBJECT_ID, HUBSPOT_ALTERNATE_ID",
Missing a couple periods?

2023-09-22 15:12 UTC, forstmeier commented on shipyard_blueprints/hubspot/shipyard_hubspot/hubspot_utils.py
> +    if column_type not in {"HUBSPOT_OBJECT_ID", "HUBSPOT_ALTERNATE_ID"}:
Could these be declared as a global variable? Something where they could be referenced/edited more easily if more column types are needed eventually.

2023-09-22 15:12 UTC, forstmeier commented on shipyard_blueprints/hubspot/shipyard_hubspot/hubspot_utils.py
> +                elif header == "hs_object_id":
Should this also be a global variable? Not familiar with HubSpot but it would be good for readability in this code.

2023-09-22 17:33 UTC, johnathan-rodriguez commented on shipyard_blueprints/hubspot/shipyard_hubspot/hubspot.py
> -        object_type: str = "contacts",
Removed the default values for object types which were causing false positive tests

2023-09-22 17:54 UTC, forstmeier approved these changes

2023-09-22 17:59 UTC, merged